{"uuid": "a81a1019-947c-432f-b8be-767c31d971c0", "children": ["7325d40b-6b01-4616-9eea-88aead41eca3"], "befores": [{"name": "driver", "status": "failed", "statusDetails": {"message": "AssertionError: Не удалось создать пользователя\nassert {}\n", "trace": "  File \"C:\\Users\\scarl\\Python\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\scarl\\Python\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\scarl\\Python\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\scarl\\Python\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\scarl\\Python\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\scarl\\PycharmProjects\\Diplom\\Diplom_3\\conftest.py\", line 19, in driver\n    assert user_data, \"Не удалось создать пользователя\"\n"}, "steps": [{"name": "Регистрируем нового юзера со случайными данными, возвращаем словарь с его именем, почтой, паролем", "status": "passed", "start": 1718053873049, "stop": 1718053873816}], "start": 1718053866425, "stop": 1718053873816}], "start": 1718053866425, "stop": 1718053873874}